AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Parameters:
  EndpointName:
    Type: String
    Default : 'sms-spam-classifier-mxnet-2020-05-07-00-34-35-823'
    Description: Please Enter your Sagemaker Endpoint
  S3BucketName:
    Type: String
    Default : 'ses-email-rn2490-cf'
    Description: Please Enter your S3 Bucket
  RuleSetName:
    Type: String
    Default : 'custom-ruleset'
    Description: Please Enter your SES Rule Set Name
  ReceiptRuleName:
    Type: String
    Default : 'ses-receipt-rule'
    Description: Please Enter your SES Receipt Name Rule Name
    

Resources:
  HW4Lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./PredictionFunction/lambda_function.py
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::041038083210:role/service-role/PredictionFunction-role-xrp8ykux'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
      Environment:
        Variables:
          ENDPOINT_NAME: 
            Ref: EndpointName

  Bucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicReadWrite
      BucketName:
        Ref: S3BucketName

  ReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: 
        Ref: RuleSetName

  SESRuleToSendMail:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: 
        Ref: RuleSetName
      Rule:
        Name: 
          Ref: ReceiptRuleName
        Actions:
          - S3Action:
              BucketName: 
                Ref: S3BucketName
        Enabled: true
        ScanEnabled: true
    DependsOn:
      - Bucket1